import = [ 
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 13

[window]
decorations = "None"

[keyboard]
bindings = [
{key = "Backspace", mods = "Control", chars = "\u0017"},
]
